### ISSUE TITLE
Contributor - Account - Create Stellar Account

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#102]
## Background 
Each contributor needs a Stellar Account in order to send and receive payments. Upon signing in with GitHub an account can be created or connected for the user. This is for stellar account creation

## Scenario: As a Contributor, I create a Stellar Account on my Account Page
- [ ] When I select to create a Stellar account 
- [ ] Then my stellar account is created
- [ ] And I see my public and private key with a warning message: 
> A Stellar Account comes with 2 keys. A public key that serves as a way for you to receive Lumens (Think Venmo username or email for PayPal) and Secret Key that gives you access to your account. This is the one and only time we will show you the secret key, please save it somewhere safe as anyone who has access to it has complete access to your account.

**Comment by bryanjos** [comment]
Some notes:
- We would need to generate a keypair for user. This is simple enough and something we can do on the frontend. They need to be able to see the generated secret. We must not be able to see it.
- There is an operation to create an account. This has to be done before sending account lumens. Accounts need a minimum balance of 1 lumen. This is where that would be applied.
- With the above we can be sure that there is already an account on the network with the same key.
- In order to prevent gaming of the system, we would need to create account at the latest possible moment. For instance when a contribution is made.
