### ISSUE TITLE
Contributor/Supporter - Account Page - Instructions for creating a Stellar account

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#89]
## Background
For MVP we are asking users to bring their own Stellar Account to the table instead of connecting via incentivize. We should provide instructions, options, links etc for providing users information on how to do this. 

## Scenario: A user without an existing stellar account lands signs into their incentivize account
- [ ] When I am directed to my Account Page 
- [ ] Then I see some instructions and useful links on creating a Stellar account 
- [ ] And I know how to connect my created stellar account to incentivize

**Comment by gerardramos** [comment]
Can we just add a line of help text to the form? Don't have a stellar account? You can create one here (helpful link) or learn more about stellar here (helpful link).

**Comment by bryanjos** [comment]
Yeah I think that should be good enough. Suprisingly, I can't find an official way to user to create an account the is more user friendly. Once they create an account and login below though, there is some instructions on loading the account with lumens. But since our intended audience is developers, this may or may not be a problem. 

This link should do:
https://www.stellar.org/account-viewer/#!/

If we can find some official instructions to go along with things, that would help as well

**Comment by bryanjos** [comment]
The set of instructions will be different if we are on test as opposed to prod. We can put both sets in and show which ever set we are on. Helps when developing locally as well
